version: '3'

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  web:
    build: .
    ports:
      - 1337:1337
    volumes:
      - ./:/app
    # command: npm start
    environment:
      - NODE_ENV=dev

volumes:
  mysql:
